version: "3.9"
services:
    db:
        image: mcr.microsoft.com/mssql/server
        container_name: mssql
        hostname: mssql-server
        volumes:
            - ./databases:/var/opt/mssql/data
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: narkizovTestDb28122020
        restart: always
    app:
        build: .
        container_name: timeTracking
        ports:
            - 5000:80
        environment:            
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_DB: Data Source=mssql-server;Initial Catalog=Tracking;User ID=sa;Password=narkizovTestDb28122020
        links:
            - db
        restart: always